using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Egil.StronglyTypedPrimitives;

[Generator]
public sealed class StronglyTypedPrimitiveGenerator : IIncrementalGenerator
{
    private static string CodeHeader { get; } = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        #nullable enable
        """;

    private const string StronglyTypedPrimitivesNamespace = "Egil.StronglyTypedPrimitives";

    private static string IStronglyTypedPrimitive => $"{StronglyTypedPrimitivesNamespace}.IStronglyTypedPrimitive`1";

    private static string IStronglyTypedPrimitiveOfSelf => $"{StronglyTypedPrimitivesNamespace}.IStronglyTypedPrimitive`2";

    private static string StronglyTypedJsonConverter => $"{StronglyTypedPrimitivesNamespace}.StronglyTypedJsonConverter";

    private static string GeneratedCodeConstructor => $@"System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(StronglyTypedPrimitiveGenerator).Assembly.FullName}"", ""{typeof(StronglyTypedPrimitiveGenerator).Assembly.GetName().Version}"")";

    private static string GeneratedCodeAttribute => $"[{GeneratedCodeConstructor}]";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var recordCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax r &&
                    r.Modifiers.Any(SyntaxKind.PartialKeyword) &&
                    r.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) &&
                    r.AttributeLists.Count > 0 &&
                    r.ParameterList?.Parameters.Count == 1,
                transform: static (context, _) =>
                {
                    var recordDecl = (RecordDeclarationSyntax)context.Node;
                    var model = context.SemanticModel;
                    return model.GetDeclaredSymbol(recordDecl) is INamedTypeSymbol symbol
                        && symbol.GetAttributes().Any(IsStronglyTypedPrimitiveAttribute)
                        && recordDecl.ParameterList?.Parameters.Count == 1
                        && recordDecl.ParameterList.Parameters[0] is { Type: not null } parameter
                        ? new StronglyTypedTypeInfo(recordDecl, Parser.GetNamespace(recordDecl), parameter.Type, parameter)
                        : null;
                }
            )
            .Where(static x => x is not null);

        // Any class with a base list is a candidate: the base type can be spelled through a using
        // alias, so matching on the written name would miss contexts. The semantic check decides.
        var hasJsonSerializerContext = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (context, cancellationToken) =>
                    context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node, cancellationToken) is INamedTypeSymbol symbol
                    && Parser.DerivesFromJsonSerializerContext(symbol))
            .Where(static x => x)
            .Collect()
            .Select(static (contexts, _) => contexts.Length > 0);

        var compilationAndRecords = context.CompilationProvider
            .Combine(recordCandidates.Collect())
            .Combine(hasJsonSerializerContext);

        context.RegisterSourceOutput(compilationAndRecords, (spc, source) =>
        {
            var ((compilation, stronglyTypedInfos), compilationHasJsonSerializerContext) = source;
            foreach (var stronglyTypedInfo in stronglyTypedInfos)
            {
                if (stronglyTypedInfo is null)
                {
                    continue;
                }

                var generated = GenerateStronglyTypedSource(stronglyTypedInfo, compilation);
                spc.AddSource($"{stronglyTypedInfo.Target.Identifier.Text}.g.cs", generated.Source);

                if (compilationHasJsonSerializerContext && generated.JsonConverterSupport is JsonConverterSupport.GenerateAttribute)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.JsonSerializerContextCannotSeeGeneratedConverter,
                        stronglyTypedInfo.Target.Identifier.GetLocation(),
                        generated.TargetTypeName,
                        generated.UnderlyingTypeName));
                }

                if (generated.JsonConverterSupport is JsonConverterSupport.SharedConverterUnavailable)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.JsonSupportRequiresNet8,
                        stronglyTypedInfo.Target.Identifier.GetLocation(),
                        generated.TargetTypeName));
                }
            }
        });
    }

    private static bool IsStronglyTypedPrimitiveAttribute(AttributeData attribute)
        => attribute.AttributeClass?.Name == "StronglyTyped"
        || attribute.AttributeClass?.Name == "StronglyTypedAttribute";

    private sealed record GeneratedSource(string Source, JsonConverterSupport JsonConverterSupport, string TargetTypeName, string UnderlyingTypeName);

    private static GeneratedSource GenerateStronglyTypedSource(StronglyTypedTypeInfo info, Compilation compilation)
    {
        const int CSharp13 = 1300;
        var isCSharp14OrGreater = compilation is CSharpCompilation cSharpCompilation && (int)cSharpCompilation.LanguageVersion > CSharp13;
        var semanticModel = compilation.GetSemanticModel(info.Target.SyntaxTree);
        var targetTypeSymbol = semanticModel.GetDeclaredSymbol(info.Target)
            ?? throw new InvalidOperationException("Cannot get type symbol for target type.");
        var underlyingTypeSymbol = semanticModel.GetTypeInfo(info.UnderlyingType).Type
            ?? throw new InvalidOperationException("Cannot get type symbol for underlying type.");
        var targetTypeMembers = targetTypeSymbol.GetMembers().ToHashSet(SymbolEqualityComparer.Default);

        var genericInterfaces = new[]
        {
            semanticModel.Compilation.GetTypeByMetadataName("System.IParsable`1"),
            semanticModel.Compilation.GetTypeByMetadataName("System.ISpanParsable`1"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IUtf8SpanParsable`1"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IComparable`1"),
        };

        var interfaces = new[]
        {
            semanticModel.Compilation.GetTypeByMetadataName("System.IComparable"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IFormattable"),
            semanticModel.Compilation.GetTypeByMetadataName("System.ISpanFormattable"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IUtf8SpanFormattable"),
        };

        var supportedGenericInterfaces = genericInterfaces
            .OfType<INamedTypeSymbol>()
            .Where(genericInterface => semanticModel.IsTypeImplementingInterface(underlyingTypeSymbol, genericInterface.Construct(underlyingTypeSymbol)));
        var supportedInterfaces = interfaces
            .OfType<INamedTypeSymbol>()
            .Where(genericInterface => semanticModel.IsTypeImplementingInterface(underlyingTypeSymbol, genericInterface));

        var selfInterface = semanticModel.Compilation
            .GetTypeByMetadataName(IStronglyTypedPrimitiveOfSelf)
            ?.Construct(targetTypeSymbol, underlyingTypeSymbol);

        var alwaysImplementInterfaces = new[]
        {
            semanticModel.Compilation
                .GetTypeByMetadataName(IStronglyTypedPrimitive)
                ?.Construct(underlyingTypeSymbol),
            selfInterface,
        };

        var interfacesToImplement = alwaysImplementInterfaces
            .OfType<INamedTypeSymbol>()
            .Concat(supportedGenericInterfaces.Select(@interface => @interface.Construct(targetTypeSymbol)))
            .Concat(supportedInterfaces)
            .ToArray();

        // The members of IStronglyTypedPrimitive<TSelf, TPrimitive> (Value and Create) have
        // dedicated generators below because they must also exist on target frameworks where the
        // interface cannot declare them (no static abstract members before net7.0).
        // IsValueValid is likewise generated from the user's members rather than from the interface:
        // the netstandard2.0 asset cannot declare it as a static abstract member, yet the generated
        // constructor validation calls it.
        var unimplementedSymbols = interfacesToImplement
            .Where(@interface => !SymbolEqualityComparer.Default.Equals(@interface, selfInterface))
            .SelectMany(@interface => semanticModel.GetUnimplementedSymbols(targetTypeMembers, @interface))
            .Where(symbol => symbol.Name != "IsValueValid")
            .ToList();
        var hasUserDeclaredIsValueValid = HasPublicStaticMethod(targetTypeMembers, "IsValueValid", underlyingTypeSymbol, compilation.GetSpecialType(SpecialType.System_Boolean), compilation.GetSpecialType(SpecialType.System_Boolean));

        var jsonConverterSupport = Parser.GetJsonConverterSupport(compilation, targetTypeSymbol);
        var targetTypeName = targetTypeSymbol.ToDisplayString();
        var underlyingTypeName = underlyingTypeSymbol.WithNullableAnnotation(NullableAnnotation.None).ToDisplayString();

        string?[] typeParts = [
            CodeHeader,
            GetNamespaceDefinition(info),
            GeneratedCodeAttribute,
            .. GetJsonConverterAttribute(jsonConverterSupport, targetTypeName, underlyingTypeName),
            GetPartialRecordStructDefinition(info, interfacesToImplement),
            "{",
            .. GetEmptyProperty(info, targetTypeMembers, underlyingTypeSymbol),
            .. GetCreateMethod(info, targetTypeMembers, targetTypeSymbol, selfInterface, underlyingTypeSymbol),
            .. GetValueProperty(info, targetTypeMembers, underlyingTypeSymbol, isCSharp14OrGreater, hasUserDeclaredIsValueValid),
            .. GetSelfInterfaceValueProperty(info, targetTypeMembers, selfInterface, underlyingTypeSymbol),
            .. GetToStringMethod(info, targetTypeMembers, underlyingTypeSymbol),
            .. GetIsValueValidMethod(underlyingTypeSymbol, hasUserDeclaredIsValueValid),
            .. GetInterfaceSymbols(info, unimplementedSymbols, underlyingTypeSymbol),
            .. GetOperatorOverloads(info, targetTypeSymbol, targetTypeMembers),
            "}"
        ];

        return new GeneratedSource(
            string.Join("\n", typeParts.OfType<string>()),
            jsonConverterSupport,
            targetTypeName,
            underlyingTypeName);
    }

    internal static string? GetNamespaceDefinition(StronglyTypedTypeInfo info)
        => info.Namespace is not null
            ? $"\nnamespace {info.Namespace};\n"
            : null;

    internal static string GetPartialRecordStructDefinition(StronglyTypedTypeInfo info, IEnumerable<INamedTypeSymbol> interfaces)
        => $"""
        {info.Target.Modifiers} record struct {info.Target.Identifier} : {string.Join(", ", interfaces.Select(x => x.ToDisplayString()))}
        """;

    internal static IEnumerable<string> GetEmptyProperty(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, ITypeSymbol underlyingTypeSymbol)
    {
        var hasEmptyProp = targetTypeMembers.OfType<IPropertySymbol>().Any(p => p.Name == "Empty" && p.IsStatic && p.Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));
        if (hasEmptyProp)
        {
            yield break;
        }

        yield return $"""
                public static readonly {info.Target.Identifier} Empty = default;
            """;
    }

    // Only a public Create(TPrimitive) satisfies IStronglyTypedPrimitive<TSelf, TPrimitive>.Create
    // implicitly. A non-public one with the same signature would clash with a generated public one,
    // so the interface member is then implemented explicitly instead (where the interface has it).
    internal static IEnumerable<string> GetCreateMethod(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, INamedTypeSymbol targetTypeSymbol, INamedTypeSymbol? selfInterface, ITypeSymbol underlyingTypeSymbol)
    {
        var interfaceCreateMethod = selfInterface?.GetMembers("Create").OfType<IMethodSymbol>().FirstOrDefault();
        var hasExplicitCreateMethod = interfaceCreateMethod is not null && targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.ExplicitInterfaceImplementations.Any(e => e.Equals(interfaceCreateMethod, SymbolEqualityComparer.Default)));
        if (hasExplicitCreateMethod || HasPublicStaticMethod(targetTypeMembers, "Create", underlyingTypeSymbol, targetTypeSymbol))
        {
            yield break;
        }

        var hasNonPublicCreateMethod = targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.Name == "Create"
                   && m.IsStatic && m.Parameters.Length == 1
                   && m.Parameters[0].Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));
        if (hasNonPublicCreateMethod)
        {
            if (interfaceCreateMethod is not null)
            {
                yield return $$"""

                        static {{info.Target.Identifier}} {{selfInterface!.ToDisplayString()}}.Create({{underlyingTypeSymbol.ToDisplayString()}} value) => new {{info.Target.Identifier}}(value);
                    """;
            }

            yield break;
        }

        yield return $$"""

                public static {{info.Target.Identifier}} Create({{underlyingTypeSymbol.ToDisplayString()}} value) => new {{info.Target.Identifier}}(value);
            """;
    }

    private static bool HasPublicStaticMethod(IEnumerable<ISymbol> targetTypeMembers, string name, ITypeSymbol firstParameterType, ITypeSymbol returnType, ITypeSymbol? secondParameterType = null)
        => targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.Name == name
                   && m.IsStatic
                   && m.DeclaredAccessibility == Accessibility.Public
                   && m.Parameters.Length == (secondParameterType is null ? 1 : 2)
                   && m.Parameters[0].Type.Equals(firstParameterType, SymbolEqualityComparer.Default)
                   && (secondParameterType is null || m.Parameters[1].Type.Equals(secondParameterType, SymbolEqualityComparer.Default))
                   && m.ReturnType.Equals(returnType, SymbolEqualityComparer.Default));

    private static IEnumerable<string> GetIsValueValidMethod(ITypeSymbol underlyingTypeSymbol, bool hasUserDeclaredIsValueValid)
    {
        if (hasUserDeclaredIsValueValid)
        {
            yield break;
        }

        yield return $$"""

            [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public static bool IsValueValid({{underlyingTypeSymbol.ToDisplayString()}} value, bool throwIfInvalid)
                => true;
        """;
    }

    internal static IEnumerable<string> GetValueProperty(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, ITypeSymbol underlyingTypeSymbol, bool isCSharp14OrGreater, bool hasUserDeclaredIsValueValid)
    {
        // The generated IsValueValid accepts everything, so the validating property wrapper is
        // only worth generating when the user supplied their own IsValueValid.
        if (!hasUserDeclaredIsValueValid)
        {
            yield break;
        }

        const string throwIfValueIsInvalidName = "ThrowIfValueIsInvalid";
        var hasThrowIfValueIsInvalid = targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.Name == throwIfValueIsInvalidName
                   && m.IsStatic && m.Parameters.Length == 1
                   && m.Parameters[0].Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default)
                   && m.ReturnType.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));

        if (!hasThrowIfValueIsInvalid)
        {
            yield return $$"""

                private static {{info.UnderlyingType}} {{throwIfValueIsInvalidName}}({{info.UnderlyingType}} value)
                {
                    IsValueValid(value, throwIfInvalid: true);
                    return value;
                }
            """;
        }

        // Check for explicit Value property declaration by end user. If they have created it
        // then the custom implementation is NOT created.
        var valueProp = targetTypeMembers.OfType<IPropertySymbol>().Single(x => x.Name == info.Parameter.Identifier.Text && x.Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));
        var valueMethods = targetTypeMembers.OfType<IMethodSymbol>().Where(x => x.AssociatedSymbol?.Equals(valueProp, SymbolEqualityComparer.Default) == true);
        if (valueMethods.Any(x => !x.IsImplicitlyDeclared))
        {
            yield break;
        }

        var fieldName = isCSharp14OrGreater ? "field" : $"@{info.Parameter.Identifier.ToString().ToLowerInvariant()}";
        var getMethodImplementation = underlyingTypeSymbol.SpecialType is SpecialType.System_String
            ? $"{fieldName} ?? string.Empty;"
            : $"{fieldName};";

        if (isCSharp14OrGreater)
        {
            yield return $$"""

                public {{info.UnderlyingType}} {{info.Parameter.Identifier}}
                {
                    get => {{getMethodImplementation}}
                    init
                    {
                        {{fieldName}} = {{throwIfValueIsInvalidName}}(value);
                    }
                } = {{throwIfValueIsInvalidName}}({{info.Parameter.Identifier}});
            """;
        }
        else
        {
            yield return $$"""

                private readonly {{info.UnderlyingType}} {{fieldName}} = {{throwIfValueIsInvalidName}}({{info.Parameter.Identifier}});

                public {{info.UnderlyingType}} {{info.Parameter.Identifier}}
                {
                    get => {{getMethodImplementation}}
                    init
                    {
                        {{fieldName}} = {{throwIfValueIsInvalidName}}(value);
                    }
                }
            """;
        }
    }

    // IStronglyTypedPrimitive<TSelf, TPrimitive>.Value is implemented implicitly by the positional
    // property when the parameter is named Value; any other name needs an explicit implementation
    // so the shared JSON converter can read the wrapped value through the interface.
    internal static IEnumerable<string> GetSelfInterfaceValueProperty(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, INamedTypeSymbol? selfInterface, ITypeSymbol underlyingTypeSymbol)
    {
        if (selfInterface?.GetMembers("Value").OfType<IPropertySymbol>().FirstOrDefault() is not { } interfaceValueProperty)
        {
            yield break;
        }

        var isImplemented = targetTypeMembers
            .OfType<IPropertySymbol>()
            .Any(p => (p.Name == "Value" && !p.IsStatic && p.GetMethod is { DeclaredAccessibility: Accessibility.Public } && p.Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default))
                   || p.ExplicitInterfaceImplementations.Any(e => e.Equals(interfaceValueProperty, SymbolEqualityComparer.Default)));
        if (isImplemented)
        {
            yield break;
        }

        yield return $$"""

                {{underlyingTypeSymbol.ToDisplayString()}} {{selfInterface.ToDisplayString()}}.Value => {{info.Parameter.Identifier}};
            """;
    }

    internal static IEnumerable<string> GetToStringMethod(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, ITypeSymbol underlyingTypeSymbol)
    {
        var toStringMethodExists = targetTypeMembers.OfType<IMethodSymbol>().Any(m => m.Name == "ToString" && !m.IsImplicitlyDeclared && m.ReturnType.SpecialType == SpecialType.System_String && m.Parameters.Length == 0);
        if (!toStringMethodExists)
        {
            yield return underlyingTypeSymbol.SpecialType is SpecialType.System_String
                ? $$"""

                    public override string ToString() => {{info.Parameter.Identifier}} ?? string.Empty;
                """
                : $$"""

                    public override string ToString() => {{info.Parameter.Identifier}}.ToString();
                """;
        }
    }

    private static IEnumerable<string> GetOperatorOverloads(StronglyTypedTypeInfo info, INamedTypeSymbol targetTypeSymbol, IEnumerable<ISymbol> targetTypeMembers)
    {
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_Equality"))
        {
            yield return $"""

                public static bool operator ==({info.Target.Identifier} a, {info.Target.Identifier} b) => a.Equals(b);
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_Inequality"))
        {
            yield return $"""

                public static bool operator !=({info.Target.Identifier} a, {info.Target.Identifier} b) => !(a == b);                
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_GreaterThan"))
        {
            yield return $"""
                
                public static bool operator > ({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) > 0;                
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_LessThan"))
        {
            yield return $"""

                public static bool operator < ({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) < 0;                
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_GreaterThanOrEqual"))
        {
            yield return $"""

                public static bool operator >=({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) >= 0;
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_LessThanOrEqual"))
        {
            yield return $"""
                
                public static bool operator <=({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) <= 0;
            """;
        }
    }

    private static IEnumerable<string> GetInterfaceSymbols(StronglyTypedTypeInfo info, IEnumerable<ISymbol> symbols, ITypeSymbol underlyingTypeSymbol)
    {
        foreach (var symbol in symbols)
        {
            if (symbol is not IMethodSymbol method)
            {
                yield return $"\n\t// Missing implementation for {symbol.OriginalDefinition.ToString()}";
                continue;
            }

            yield return method switch
            {

                { Name: "Parse", Parameters: { Length: 2 } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringParse(info, method, underlyingTypeSymbol),
                { Name: "TryParse", Parameters: { Length: 3 } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringTryParse(info, method, underlyingTypeSymbol),

                { Name: "Parse", Parameters: { Length: 2 } } => GetParse(info, method, underlyingTypeSymbol),
                { Name: "TryParse", Parameters: { Length: 3 } } => GetTryParse(info, method, underlyingTypeSymbol),

                { Name: "CompareTo", ContainingType: { IsGenericType: true } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringCompareToOfT(info, method, underlyingTypeSymbol),
                { Name: "CompareTo", ContainingType: { IsGenericType: false } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringCompareTo(info, method, underlyingTypeSymbol),

                { Name: "CompareTo", ContainingType: { IsGenericType: true } } => GetCompareToOfT(info, method, underlyingTypeSymbol),
                { Name: "CompareTo", ContainingType: { IsGenericType: false } } => GetCompareTo(info, method, underlyingTypeSymbol),
                { Name: "ToString", Parameters: { Length: 2 } } => GetToString(info, method, underlyingTypeSymbol),
                { Name: "TryFormat", Parameters: { Length: 4 } } => GetTryFormat(info, method, underlyingTypeSymbol),

                _ => $"\n\t// Missing implementation for {symbol.OriginalDefinition.ToString()}",
            };
        }
    }


    private static string GetParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""

            public static {{info.Target.Identifier}} Parse({{method.Parameters[0]}}, {{method.Parameters[1]}})
            {
                var rawValue = {{underlyingTypeSymbol.ToDisplayString()}}.Parse({{method.Parameters[0].Name}}, {{method.Parameters[1].Name}});
                IsValueValid(rawValue, throwIfInvalid: true);
                return new {{info.Target.Identifier}}(rawValue);
            }
        """;

    private static string GetTryParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""

            public static bool TryParse({{method.Parameters[0]}}, {{method.Parameters[1]}}, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] {{method.Parameters[2]}})
            {
                if ({{underlyingTypeSymbol.ToDisplayString()}}.TryParse({{method.Parameters[0].Name}}, {{method.Parameters[1].Name}}, out var rawValue) && IsValueValid(rawValue, throwIfInvalid: false))
                {
                    {{method.Parameters[2].Name}} = new {{info.Target.Identifier}}(rawValue);
                    return true;
                }

                {{method.Parameters[2].Name}} = {{info.Target.Identifier}}.Empty;
                return false;
            }
        """;

    private static string GetStringParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
    {
        var rawValueString = method.Parameters[0].Type switch
        {
            { SpecialType: SpecialType.System_String } => $"{method.Parameters[0].Name}",
            _ => $"{method.Parameters[0].Name}.ToString()",
        };

        return $$"""

            public static {{info.Target.Identifier}} Parse({{method.Parameters[0]}}, {{method.Parameters[1]}})
            {
                var rawValue = {{rawValueString}};
                IsValueValid(rawValue, throwIfInvalid: true);
                return new {{info.Target.Identifier}}(rawValue);
            }
        """;
    }

    private static string GetStringTryParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
    {
        var rawValueString = method.Parameters[0].Type switch
        {
            { SpecialType: SpecialType.System_String } => $"{method.Parameters[0].Name}",
            _ => $"{method.Parameters[0].Name}.ToString()",
        };
        return $$"""

            public static bool TryParse({{method.Parameters[0]}}, {{method.Parameters[1]}}, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] {{method.Parameters[2]}})
            {
                if ({{rawValueString}} is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
                {
                    {{method.Parameters[2].Name}} = new {{info.Target.Identifier}}(rawValue);
                    return true;
                }

                {{method.Parameters[2].Name}} = {{info.Target.Identifier}}.Empty;
                return false;
            }
        """;
    }

    private static string GetStringCompareToOfT(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
    => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
            => ({{info.Parameter.Identifier}} ?? string.Empty).CompareTo({{method.Parameters[0].Name}}.{{info.Parameter.Identifier}});
    """;

    private static string GetStringCompareTo(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
        {
            if ({{method.Parameters[0].Name}} is null)
            {
                return 1;
            }

            if ({{method.Parameters[0].Name}} is {{info.Target.Identifier}} other)
            {
                return ({{info.Parameter.Identifier}} ?? string.Empty).CompareTo(other.{{info.Parameter.Identifier}});
            }

            return (({{method.ContainingType.ToDisplayString()}})({{info.Parameter.Identifier}} ?? string.Empty)).CompareTo({{method.Parameters[0].Name}});
        }
    """;

    private static string GetCompareToOfT(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
            => {{info.Parameter.Identifier}}.CompareTo({{method.Parameters[0].Name}}.{{info.Parameter.Identifier}});
    """;

    private static string GetCompareTo(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
        {
            if ({{method.Parameters[0].Name}} is null)
            {
                return 1;
            }

            if ({{method.Parameters[0].Name}} is {{info.Target.Identifier}} other)
            {
                return {{info.Parameter.Identifier}}.CompareTo(other.{{info.Parameter.Identifier}});
            }

            return (({{method.ContainingType.ToDisplayString()}}){{info.Parameter.Identifier}}).CompareTo({{method.Parameters[0].Name}});
        }
    """;

    private static string GetToString(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public string ToString({{method.Parameters[0]}}, {{method.Parameters[1]}})
            => {{info.Parameter.Identifier}}.ToString({{method.Parameters[0].Name}}, {{method.Parameters[1].Name}});
    """;

    private static string GetTryFormat(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public bool TryFormat({{method.Parameters[0]}}, {{method.Parameters[1]}}, {{method.Parameters[2]}}, {{method.Parameters[3]}})
            => (({{method.ContainingType.ToDisplayString()}}){{info.Parameter.Identifier}}).TryFormat({{method.Parameters[0].Name}}, out {{method.Parameters[1].Name}}, {{method.Parameters[2].Name}}, {{method.Parameters[3].Name}});
    """;

    // The converter is declared by attribute instead of being emitted per type so the generated
    // code stays trim/AOT clean, and so the same converter can be declared by hand for types that
    // are serialized through a JsonSerializerContext.
    private static IEnumerable<string> GetJsonConverterAttribute(JsonConverterSupport jsonConverterSupport, string targetTypeName, string underlyingTypeName)
    {
        if (jsonConverterSupport is not JsonConverterSupport.GenerateAttribute)
        {
            yield break;
        }

        yield return $$"""
            [System.Text.Json.Serialization.JsonConverterAttribute(typeof({{StronglyTypedJsonConverter}}<{{targetTypeName}}, {{underlyingTypeName}}>))]
            """;
    }
}