using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Egil.StronglyTypedPrimitives;

[Generator]
public sealed class StronglyTypedPrimitiveGenerator : IIncrementalGenerator
{
    private static string CodeHeader { get; } = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        #nullable enable
        """;

    private const string StronglyTypedPrimitivesNamespace = "Egil.StronglyTypedPrimitives";

    private static string IStronglyTypedPrimitive => $"{StronglyTypedPrimitivesNamespace}.IStronglyTypedPrimitive`1";

    private static string IStronglyTypedPrimitiveOfSelf => $"{StronglyTypedPrimitivesNamespace}.IStronglyTypedPrimitive`2";

    private static string StronglyTypedJsonConverter => $"{StronglyTypedPrimitivesNamespace}.StronglyTypedJsonConverter";

    private static string GeneratedCodeConstructor => $@"System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(StronglyTypedPrimitiveGenerator).Assembly.FullName}"", ""{typeof(StronglyTypedPrimitiveGenerator).Assembly.GetName().Version}"")";

    private static string GeneratedCodeAttribute => $"[{GeneratedCodeConstructor}]";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var recordCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax r &&
                    r.Modifiers.Any(SyntaxKind.PartialKeyword) &&
                    r.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) &&
                    r.AttributeLists.Count > 0 &&
                    r.ParameterList?.Parameters.Count == 1,
                transform: static (context, _) =>
                {
                    var recordDecl = (RecordDeclarationSyntax)context.Node;
                    var model = context.SemanticModel;
                    return model.GetDeclaredSymbol(recordDecl) is INamedTypeSymbol symbol
                        && symbol.GetAttributes().Any(IsStronglyTypedPrimitiveAttribute)
                        && recordDecl.ParameterList?.Parameters.Count == 1
                        && recordDecl.ParameterList.Parameters[0] is { Type: not null } parameter
                        ? new StronglyTypedTypeInfo(recordDecl, Parser.GetNamespace(recordDecl), parameter.Type, parameter)
                        : null;
                }
            )
            .Where(static x => x is not null);

        // Any class with a base list is a candidate: the base type can be spelled through a using
        // alias, so matching on the written name would miss contexts. The semantic check decides.
        var hasJsonSerializerContext = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (context, cancellationToken) =>
                    context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node, cancellationToken) is INamedTypeSymbol symbol
                    && Parser.DerivesFromJsonSerializerContext(symbol))
            .Where(static x => x)
            .Collect()
            .Select(static (contexts, _) => contexts.Length > 0);

        var compilationAndRecords = context.CompilationProvider
            .Combine(recordCandidates.Collect())
            .Combine(hasJsonSerializerContext);

        context.RegisterSourceOutput(compilationAndRecords, (spc, source) =>
        {
            var ((compilation, stronglyTypedInfos), compilationHasJsonSerializerContext) = source;
            foreach (var stronglyTypedInfo in stronglyTypedInfos)
            {
                if (stronglyTypedInfo is null)
                {
                    continue;
                }

                var generated = GenerateStronglyTypedSource(stronglyTypedInfo, compilation);
                spc.AddSource($"{stronglyTypedInfo.Target.Identifier.Text}.g.cs", generated.Source);

                foreach (var diagnostic in generated.Diagnostics)
                {
                    spc.ReportDiagnostic(diagnostic);
                }

                if (compilationHasJsonSerializerContext && generated.JsonConverterSupport is JsonConverterSupport.GenerateAttribute)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.JsonSerializerContextCannotSeeGeneratedConverter,
                        stronglyTypedInfo.Target.Identifier.GetLocation(),
                        generated.TargetTypeName,
                        generated.UnderlyingTypeName));
                }

                if (generated.JsonConverterSupport is JsonConverterSupport.SharedConverterUnavailable)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.JsonSupportRequiresNet8,
                        stronglyTypedInfo.Target.Identifier.GetLocation(),
                        generated.TargetTypeName));
                }
            }
        });
    }

    private static bool IsStronglyTypedPrimitiveAttribute(AttributeData attribute)
        => attribute.AttributeClass?.Name == "StronglyTyped"
        || attribute.AttributeClass?.Name == "StronglyTypedAttribute";

    private sealed record GeneratedSource(
        string Source,
        JsonConverterSupport JsonConverterSupport,
        string TargetTypeName,
        string UnderlyingTypeName,
        ImmutableArray<Diagnostic> Diagnostics);

    private static GeneratedSource GenerateStronglyTypedSource(StronglyTypedTypeInfo info, Compilation compilation)
    {
        const int CSharp13 = 1300;
        var isCSharp14OrGreater = compilation is CSharpCompilation cSharpCompilation && (int)cSharpCompilation.LanguageVersion > CSharp13;
        var semanticModel = compilation.GetSemanticModel(info.Target.SyntaxTree);
        var targetTypeSymbol = semanticModel.GetDeclaredSymbol(info.Target)
            ?? throw new InvalidOperationException("Cannot get type symbol for target type.");
        var underlyingTypeSymbol = semanticModel.GetTypeInfo(info.UnderlyingType).Type
            ?? throw new InvalidOperationException("Cannot get type symbol for underlying type.");
        var targetTypeMembers = targetTypeSymbol.GetMembers().ToHashSet(SymbolEqualityComparer.Default);

        var genericInterfaces = new[]
        {
            semanticModel.Compilation.GetTypeByMetadataName("System.IParsable`1"),
            semanticModel.Compilation.GetTypeByMetadataName("System.ISpanParsable`1"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IUtf8SpanParsable`1"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IComparable`1"),
        };

        var interfaces = new[]
        {
            semanticModel.Compilation.GetTypeByMetadataName("System.IComparable"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IFormattable"),
            semanticModel.Compilation.GetTypeByMetadataName("System.ISpanFormattable"),
            semanticModel.Compilation.GetTypeByMetadataName("System.IUtf8SpanFormattable"),
        };

        var supportedGenericInterfaces = genericInterfaces
            .OfType<INamedTypeSymbol>()
            .Where(genericInterface => semanticModel.IsTypeImplementingInterface(underlyingTypeSymbol, genericInterface.Construct(underlyingTypeSymbol)));
        var supportedInterfaces = interfaces
            .OfType<INamedTypeSymbol>()
            .Where(genericInterface => semanticModel.IsTypeImplementingInterface(underlyingTypeSymbol, genericInterface));

        var selfInterface = semanticModel.Compilation
            .GetTypeByMetadataName(IStronglyTypedPrimitiveOfSelf)
            ?.Construct(targetTypeSymbol, underlyingTypeSymbol);

        var alwaysImplementInterfaces = new[]
        {
            semanticModel.Compilation
                .GetTypeByMetadataName(IStronglyTypedPrimitive)
                ?.Construct(underlyingTypeSymbol),
            selfInterface,
        };

        var interfacesToImplement = alwaysImplementInterfaces
            .OfType<INamedTypeSymbol>()
            .Concat(supportedGenericInterfaces.Select(@interface => @interface.Construct(targetTypeSymbol)))
            .Concat(supportedInterfaces)
            .ToArray();

        // The members of IStronglyTypedPrimitive<TSelf, TPrimitive> (Value and Create) have
        // dedicated generators below because they must also exist on target frameworks where the
        // interface cannot declare them (no static abstract members before net7.0).
        // IsValueValid is likewise generated from the user's members rather than from the interface:
        // the netstandard2.0 asset cannot declare it as a static abstract member, yet the generated
        // constructor validation calls it.
        var unimplementedSymbols = interfacesToImplement
            .Where(@interface => !SymbolEqualityComparer.Default.Equals(@interface, selfInterface))
            .SelectMany(@interface => semanticModel.GetUnimplementedSymbols(targetTypeMembers, @interface))
            .Where(symbol => symbol.Name != "IsValueValid")
            .ToList();
        var hasUserDeclaredIsValueValid = HasPublicStaticMethod(targetTypeMembers, "IsValueValid", underlyingTypeSymbol, compilation.GetSpecialType(SpecialType.System_Boolean), compilation.GetSpecialType(SpecialType.System_Boolean));

        var jsonConverterSupport = Parser.GetJsonConverterSupport(compilation, targetTypeSymbol);
        var targetTypeName = targetTypeSymbol.ToDisplayString();
        var underlyingTypeName = underlyingTypeSymbol.WithNullableAnnotation(NullableAnnotation.None).ToDisplayString();

        var validationAttributes = Parser.GetValidationAttributes(info.Parameter, semanticModel, targetTypeMembers);
        var generatesValidate = Parser.ShouldGenerateValidate(compilation, targetTypeSymbol);
        var diagnostics = GetValidationAttributeDiagnostics(info, validationAttributes, hasUserDeclaredIsValueValid);

        string?[] typeParts = [
            CodeHeader,
            GetNamespaceDefinition(info),
            GeneratedCodeAttribute,
            .. GetJsonConverterAttribute(jsonConverterSupport, targetTypeName, underlyingTypeName),
            GetPartialRecordStructDefinition(info, interfacesToImplement),
            "{",
            .. GetEmptyMember(info, targetTypeMembers, targetTypeSymbol, selfInterface),
            .. GetCreateMethod(info, targetTypeMembers, targetTypeSymbol, selfInterface, underlyingTypeSymbol),
            .. GetValueProperty(info, targetTypeMembers, underlyingTypeSymbol, isCSharp14OrGreater, hasUserDeclaredIsValueValid, validationAttributes),
            .. GetSelfInterfaceValueProperty(info, targetTypeMembers, selfInterface, underlyingTypeSymbol),
            .. GetToStringMethod(info, targetTypeMembers, underlyingTypeSymbol),
            .. GetValidatorsClass(validationAttributes, generatesValidate, hasUserDeclaredIsValueValid),
            .. GetIsValueValidMethod(info, underlyingTypeSymbol, hasUserDeclaredIsValueValid, validationAttributes),
            .. GetInterfaceSymbols(info, unimplementedSymbols, underlyingTypeSymbol),
            .. GetValidateMethod(info, targetTypeMembers, generatesValidate, hasUserDeclaredIsValueValid, validationAttributes),
            .. GetOperatorOverloads(info, targetTypeSymbol, targetTypeMembers),
            "}"
        ];

        return new GeneratedSource(
            string.Join("\n", typeParts.OfType<string>()),
            jsonConverterSupport,
            targetTypeName,
            underlyingTypeName,
            diagnostics);
    }

    private static ImmutableArray<Diagnostic> GetValidationAttributeDiagnostics(StronglyTypedTypeInfo info, ValidationAttributeModel validationAttributes, bool hasUserDeclaredIsValueValid)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var typeName = info.Target.Identifier.Text;
        var parameterName = info.Parameter.Identifier.Text;

        if (hasUserDeclaredIsValueValid)
        {
            foreach (var attribute in validationAttributes.Attributes)
            {
                diagnostics.Add(Diagnostic.Create(
                    DiagnosticDescriptors.ValidationAttributesIgnoredByUserIsValueValid,
                    attribute.Location,
                    attribute.AttributeDisplayName,
                    parameterName,
                    typeName));
            }
        }

        foreach (var attribute in validationAttributes.AsyncAttributes)
        {
            diagnostics.Add(Diagnostic.Create(
                DiagnosticDescriptors.AsyncValidationAttributeNotPartOfValueInvariant,
                attribute.Location,
                attribute.AttributeDisplayName,
                parameterName,
                typeName));
        }

        foreach (var attribute in validationAttributes.ContextAttributes)
        {
            diagnostics.Add(Diagnostic.Create(
                DiagnosticDescriptors.ContextValidationAttributeNotPartOfValueInvariant,
                attribute.Location,
                attribute.AttributeDisplayName,
                parameterName,
                typeName));
        }

        return diagnostics.ToImmutable();
    }

    internal static string? GetNamespaceDefinition(StronglyTypedTypeInfo info)
        => info.Namespace is not null
            ? $"\nnamespace {info.Namespace};\n"
            : null;

    internal static string GetPartialRecordStructDefinition(StronglyTypedTypeInfo info, IEnumerable<INamedTypeSymbol> interfaces)
        => $"""
        {info.Target.Modifiers} record struct {info.Target.Identifier} : {string.Join(", ", interfaces.Select(x => x.ToDisplayString()))}
        """;

    // The generated Empty is a static field, so a user replaces it by declaring any static field or
    // property of that name. Its type is deliberately not checked: the generated members reference
    // Empty by name, so a differently typed member fails at those references with a clear error
    // instead of colliding with a second Empty (CS0102).
    internal static IEnumerable<string> GetEmptyMember(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, INamedTypeSymbol targetTypeSymbol, INamedTypeSymbol? selfInterface)
    {
        var userDeclaredEmpty = targetTypeMembers
            .Where(m => m.Name == "Empty" && m.IsStatic)
            .FirstOrDefault(m => m is IFieldSymbol or IPropertySymbol);
        if (userDeclaredEmpty is null)
        {
            yield return $"""
                    public static readonly {info.Target.Identifier} Empty = default;
                """;
            yield break;
        }

        // IStronglyTypedPrimitive<TSelf, TPrimitive>.Empty is a static virtual property whose default
        // implementation returns default(TSelf), which is also what the generated field holds, so the
        // generated field needs no forwarding. A user-declared public static property of the target
        // type implements the interface member implicitly, but a field or a non-public property
        // cannot, so the interface member is forwarded explicitly; otherwise generic code such as the
        // shared JSON converter would see default(TSelf) instead of the user's Empty.
        var interfaceEmptyProperty = selfInterface?.GetMembers("Empty").OfType<IPropertySymbol>().FirstOrDefault();
        if (interfaceEmptyProperty is null)
        {
            yield break;
        }

        var implementsInterfaceEmptyImplicitly = userDeclaredEmpty is IPropertySymbol { DeclaredAccessibility: Accessibility.Public } property
            && property.Type.Equals(targetTypeSymbol, SymbolEqualityComparer.Default);
        var hasExplicitInterfaceEmpty = targetTypeMembers
            .OfType<IPropertySymbol>()
            .Any(p => p.ExplicitInterfaceImplementations.Any(e => e.Equals(interfaceEmptyProperty, SymbolEqualityComparer.Default)));
        if (implementsInterfaceEmptyImplicitly || hasExplicitInterfaceEmpty)
        {
            yield break;
        }

        yield return $$"""

                static {{info.Target.Identifier}} {{selfInterface!.ToDisplayString()}}.Empty => Empty;
            """;
    }

    // Only a public Create(TPrimitive) satisfies IStronglyTypedPrimitive<TSelf, TPrimitive>.Create
    // implicitly. A non-public one with the same signature would clash with a generated public one,
    // so the interface member is then implemented explicitly instead (where the interface has it).
    internal static IEnumerable<string> GetCreateMethod(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, INamedTypeSymbol targetTypeSymbol, INamedTypeSymbol? selfInterface, ITypeSymbol underlyingTypeSymbol)
    {
        var interfaceCreateMethod = selfInterface?.GetMembers("Create").OfType<IMethodSymbol>().FirstOrDefault();
        var hasExplicitCreateMethod = interfaceCreateMethod is not null && targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.ExplicitInterfaceImplementations.Any(e => e.Equals(interfaceCreateMethod, SymbolEqualityComparer.Default)));
        if (hasExplicitCreateMethod || HasPublicStaticMethod(targetTypeMembers, "Create", underlyingTypeSymbol, targetTypeSymbol))
        {
            yield break;
        }

        var hasNonPublicCreateMethod = targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.Name == "Create"
                   && m.IsStatic && IsNonGenericByValue(m) && m.Parameters.Length == 1
                   && m.Parameters[0].Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));
        if (hasNonPublicCreateMethod)
        {
            if (interfaceCreateMethod is not null)
            {
                yield return $$"""

                        static {{info.Target.Identifier}} {{selfInterface!.ToDisplayString()}}.Create({{underlyingTypeSymbol.ToDisplayString()}} value) => new {{info.Target.Identifier}}(value);
                    """;
            }

            yield break;
        }

        yield return $$"""

                public static {{info.Target.Identifier}} Create({{underlyingTypeSymbol.ToDisplayString()}} value) => new {{info.Target.Identifier}}(value);
            """;
    }

    private static bool HasPublicStaticMethod(IEnumerable<ISymbol> targetTypeMembers, string name, ITypeSymbol firstParameterType, ITypeSymbol returnType, ITypeSymbol? secondParameterType = null)
        => targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.Name == name
                   && m.IsStatic
                   && m.DeclaredAccessibility == Accessibility.Public
                   && IsNonGenericByValue(m)
                   && m.Parameters.Length == (secondParameterType is null ? 1 : 2)
                   && m.Parameters[0].Type.Equals(firstParameterType, SymbolEqualityComparer.Default)
                   && (secondParameterType is null || m.Parameters[1].Type.Equals(secondParameterType, SymbolEqualityComparer.Default))
                   && m.ReturnType.Equals(returnType, SymbolEqualityComparer.Default));

    // A generic method or one taking its parameters by reference is a different overload from the
    // member the generator would emit, so it is not a replacement for it: treating `Create<T>(int)`
    // or `Create(ref int)` as the implementation of the static abstract `Create(int)` would skip
    // generation and leave the interface unimplemented (CS0535).
    private static bool IsNonGenericByValue(IMethodSymbol method)
        => !method.IsGenericMethod && method.Parameters.All(p => p.RefKind == RefKind.None);

    // The attributes that the generated IsValueValid evaluates: none when the user wrote the
    // method themselves, in which case the attributes are reported as ignored (STP002).
    private static ImmutableArray<ValidationAttributeInfo> GetInvariantAttributes(ValidationAttributeModel validationAttributes, bool hasUserDeclaredIsValueValid)
        => hasUserDeclaredIsValueValid ? ImmutableArray<ValidationAttributeInfo>.Empty : validationAttributes.Attributes;

    // The attributes that need a ValidationContext are evaluated by the generated Validate only,
    // so they matter only when that method is generated.
    private static ImmutableArray<ValidationAttributeInfo> GetContextAttributes(ValidationAttributeModel validationAttributes, bool generatesValidate)
        => generatesValidate ? validationAttributes.ContextAttributes : ImmutableArray<ValidationAttributeInfo>.Empty;

    // The attribute instances sit in a nested static class, not on the target type: a user's
    // static initializer such as `public static readonly Foo Default = new(1);` calls IsValueValid
    // while the target type is still initializing, and whether the generated part's fields are
    // assigned by then depends on the order the compiler gives the partial declarations. The
    // nested class initializes on its first use, so the validators are ready whenever a generated
    // method runs. Only attributes a generated method reads get a field, so the class is absent
    // when nothing would use it. The factory for the ValidationContext that IsValueValid evaluates
    // the invariant attributes against lives here too, and only when that method has attributes
    // to evaluate; Validate uses the context its caller passes instead.
    private static IEnumerable<string> GetValidatorsClass(ValidationAttributeModel validationAttributes, bool generatesValidate, bool hasUserDeclaredIsValueValid)
    {
        var invariantAttributes = GetInvariantAttributes(validationAttributes, hasUserDeclaredIsValueValid);
        var attributes = invariantAttributes.AddRange(GetContextAttributes(validationAttributes, generatesValidate));
        if (attributes.IsEmpty)
        {
            yield break;
        }

        var context = validationAttributes.InvariantContext;
        var source = new StringBuilder();
        source.Append($"\n    private static class {validationAttributes.ValidatorsTypeName}\n    {{");

        foreach (var attribute in attributes)
        {
            source.Append($"\n        public static readonly {attribute.AttributeTypeName} {attribute.FieldName} = {attribute.CreationExpression};");
        }

        if (!invariantAttributes.IsEmpty)
        {
            source.Append('\n');

            if (context.SuppressTrimWarning)
            {
                source.Append("\n        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"DisplayName is set, so the constructor's reflection fallback for it never runs.\")]");
            }

            source.Append($"\n        public static global::System.ComponentModel.DataAnnotations.ValidationContext {context.FactoryMethodName}()\n            => {context.CreationExpression};");
        }

        source.Append("\n    }");

        yield return source.ToString();
    }

    private static IEnumerable<string> GetIsValueValidMethod(StronglyTypedTypeInfo info, ITypeSymbol underlyingTypeSymbol, bool hasUserDeclaredIsValueValid, ValidationAttributeModel validationAttributes)
    {
        if (hasUserDeclaredIsValueValid)
        {
            yield break;
        }

        if (validationAttributes.Attributes.IsEmpty)
        {
            yield return $$"""

                [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                public static bool IsValueValid({{underlyingTypeSymbol.ToDisplayString()}} value, bool throwIfInvalid)
                    => true;
            """;
            yield break;
        }

        // Each attribute gets its own check and error local so the method stays a flat sequence
        // of statements: no collections, loops or helpers to trim or allocate. With throwIfInvalid
        // the checks keep going after a failure so the exception can report every violated
        // attribute at once; without it the first failure is the answer.
        //
        // The attributes are called through GetValidationResult with a context rather than through
        // IsValid(object): an attribute that overrides only IsValid(object, ValidationContext) would
        // be handed a null context by IsValid(object) and fail with a NullReferenceException.
        // GetValidationResult serves both overload styles the way Validator does, allocates nothing
        // on failure-free runs beyond the context itself (Success is null) and returns a message
        // already formatted with the display name, so there is no FormatErrorMessage call either.
        // The context is created per call: it is mutable and an attribute may write to it, so a
        // shared instance would leak state between validations and race between threads.
        //
        // A non-null result is a failure even when its ErrorMessage is null. GetValidationResult
        // substitutes FormatErrorMessage for an empty message, so that only happens when the
        // attribute's FormatErrorMessage returns null too, but the error locals double as the
        // "did it fail" flags, so a null there would turn the failure into a pass. The fallback
        // wording is the one ValidationAttribute itself uses when no message is configured.
        var attributes = validationAttributes.Attributes;
        var validators = validationAttributes.ValidatorsTypeName;
        var context = validationAttributes.InvariantContext;
        var fallbackMessage = SymbolDisplay.FormatLiteral($"The field {info.Parameter.Identifier.ValueText} is invalid.", quote: true);
        var source = new StringBuilder();

        source.Append($"\n    public static bool IsValueValid({underlyingTypeSymbol.ToDisplayString()} value, bool throwIfInvalid)\n    {{");
        source.Append($"\n        var context = {validators}.{context.FactoryMethodName}();");

        foreach (var attribute in attributes)
        {
            source.Append($"\n        string? error{attribute.Index} = null;");
        }

        source.Append('\n');

        foreach (var attribute in attributes)
        {
            source.Append($$"""

                        if ({{validators}}.{{attribute.FieldName}}.GetValidationResult(value, context) is { } result{{attribute.Index}})
                        {
                            if (!throwIfInvalid) return false;
                            error{{attribute.Index}} = result{{attribute.Index}}.ErrorMessage ?? {{fallbackMessage}};
                        }

                """);
        }

        source.Append($"\n        if ({string.Join(" && ", attributes.Select(attribute => $"error{attribute.Index} is null"))}) return true;");
        source.Append("\n\n        var message = string.Empty;");

        foreach (var attribute in attributes)
        {
            source.Append(attribute.Index == 0
                ? $"\n        if (error0 is not null) message = error0;"
                : $"\n        if (error{attribute.Index} is not null) message = message.Length == 0 ? error{attribute.Index} : message + global::System.Environment.NewLine + error{attribute.Index};");
        }

        source.Append("\n        throw new global::System.ComponentModel.DataAnnotations.ValidationException(message, null, value);\n    }");

        yield return source.ToString();
    }

    internal static IEnumerable<string> GetValueProperty(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, ITypeSymbol underlyingTypeSymbol, bool isCSharp14OrGreater, bool hasUserDeclaredIsValueValid, ValidationAttributeModel validationAttributes)
    {
        // Without a user-written IsValueValid or validation attributes every value is valid, so
        // the positional property is left to the compiler instead of routing it through a check
        // that always passes.
        if (!hasUserDeclaredIsValueValid && validationAttributes.Attributes.IsEmpty)
        {
            yield break;
        }

        const string throwIfValueIsInvalidName = "ThrowIfValueIsInvalid";
        var hasThrowIfValueIsInvalid = targetTypeMembers
            .OfType<IMethodSymbol>()
            .Any(m => m.Name == throwIfValueIsInvalidName
                   && m.IsStatic && m.Parameters.Length == 1
                   && m.Parameters[0].Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default)
                   && m.ReturnType.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));

        if (!hasThrowIfValueIsInvalid)
        {
            yield return $$"""

                private static {{info.UnderlyingType}} {{throwIfValueIsInvalidName}}({{info.UnderlyingType}} value)
                {
                    IsValueValid(value, throwIfInvalid: true);
                    return value;
                }
            """;
        }

        // Check for explicit Value property declaration by end user. If they have created it
        // then the custom implementation is NOT created.
        var valueProp = targetTypeMembers.OfType<IPropertySymbol>().Single(x => x.Name == info.Parameter.Identifier.Text && x.Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default));
        var valueMethods = targetTypeMembers.OfType<IMethodSymbol>().Where(x => x.AssociatedSymbol?.Equals(valueProp, SymbolEqualityComparer.Default) == true);
        if (valueMethods.Any(x => !x.IsImplicitlyDeclared))
        {
            yield break;
        }

        // Before the field keyword the backing field is the parameter name in lower case, which is
        // the parameter's own name when the user wrote it in lower case already (int value, int
        // result0), so the same underscore suffixing as the validator fields keeps it distinct.
        // "value" is reserved as well: inside the init accessor it is the implicit parameter, and
        // @value is the same identifier, so a field of that name would be shadowed and the
        // accessor would assign to its own parameter, leaving `x with { Value = v }` a no-op.
        var reservedFieldNames = new HashSet<string>(targetTypeMembers.Select(member => member.Name), StringComparer.Ordinal) { "value" };
        var fieldName = isCSharp14OrGreater ? "field" : $"@{Parser.GetUnusedName(info.Parameter.Identifier.Text.ToLowerInvariant(), reservedFieldNames)}";
        var getMethodImplementation = underlyingTypeSymbol.SpecialType is SpecialType.System_String
            ? $"{fieldName} ?? string.Empty;"
            : $"{fieldName};";

        if (isCSharp14OrGreater)
        {
            yield return $$"""

                public {{info.UnderlyingType}} {{info.Parameter.Identifier}}
                {
                    get => {{getMethodImplementation}}
                    init
                    {
                        {{fieldName}} = {{throwIfValueIsInvalidName}}(value);
                    }
                } = {{throwIfValueIsInvalidName}}({{info.Parameter.Identifier}});
            """;
        }
        else
        {
            yield return $$"""

                private readonly {{info.UnderlyingType}} {{fieldName}} = {{throwIfValueIsInvalidName}}({{info.Parameter.Identifier}});

                public {{info.UnderlyingType}} {{info.Parameter.Identifier}}
                {
                    get => {{getMethodImplementation}}
                    init
                    {
                        {{fieldName}} = {{throwIfValueIsInvalidName}}(value);
                    }
                }
            """;
        }
    }

    // IStronglyTypedPrimitive<TSelf, TPrimitive>.Value must expose the wrapped (positional) value,
    // because the shared JSON converter serializes whatever it reads through the interface. Only
    // the positional property itself may implement it implicitly, which is the case when the
    // parameter is named Value. Any other public Value property (say a computed one next to a
    // parameter named Celsius) would otherwise satisfy the interface and be serialized in place of
    // the wrapped value, so an explicit implementation forwarding to the positional property is
    // emitted instead, unless the user implemented the interface member explicitly themselves.
    internal static IEnumerable<string> GetSelfInterfaceValueProperty(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, INamedTypeSymbol? selfInterface, ITypeSymbol underlyingTypeSymbol)
    {
        if (selfInterface?.GetMembers("Value").OfType<IPropertySymbol>().FirstOrDefault() is not { } interfaceValueProperty)
        {
            yield break;
        }

        var positionalPropertyIsValue = info.Parameter.Identifier.Text == "Value";
        var isImplemented = targetTypeMembers
            .OfType<IPropertySymbol>()
            .Any(p => (positionalPropertyIsValue && p.Name == "Value" && !p.IsStatic && p.GetMethod is { DeclaredAccessibility: Accessibility.Public } && p.Type.Equals(underlyingTypeSymbol, SymbolEqualityComparer.Default))
                   || p.ExplicitInterfaceImplementations.Any(e => e.Equals(interfaceValueProperty, SymbolEqualityComparer.Default)));
        if (isImplemented)
        {
            yield break;
        }

        yield return $$"""

                {{underlyingTypeSymbol.ToDisplayString()}} {{selfInterface.ToDisplayString()}}.Value => {{info.Parameter.Identifier}};
            """;
    }

    internal static IEnumerable<string> GetToStringMethod(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, ITypeSymbol underlyingTypeSymbol)
    {
        var toStringMethodExists = targetTypeMembers.OfType<IMethodSymbol>().Any(m => m.Name == "ToString" && !m.IsImplicitlyDeclared && m.ReturnType.SpecialType == SpecialType.System_String && m.Parameters.Length == 0);
        if (!toStringMethodExists)
        {
            yield return underlyingTypeSymbol.SpecialType is SpecialType.System_String
                ? $$"""

                    public override string ToString() => {{info.Parameter.Identifier}} ?? string.Empty;
                """
                : $$"""

                    public override string ToString() => {{info.Parameter.Identifier}}.ToString();
                """;
        }
    }

    private static IEnumerable<string> GetOperatorOverloads(StronglyTypedTypeInfo info, INamedTypeSymbol targetTypeSymbol, IEnumerable<ISymbol> targetTypeMembers)
    {
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_Equality"))
        {
            yield return $"""

                public static bool operator ==({info.Target.Identifier} a, {info.Target.Identifier} b) => a.Equals(b);
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_Inequality"))
        {
            yield return $"""

                public static bool operator !=({info.Target.Identifier} a, {info.Target.Identifier} b) => !(a == b);                
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_GreaterThan"))
        {
            yield return $"""
                
                public static bool operator > ({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) > 0;                
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_LessThan"))
        {
            yield return $"""

                public static bool operator < ({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) < 0;                
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_GreaterThanOrEqual"))
        {
            yield return $"""

                public static bool operator >=({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) >= 0;
            """;
        }
        if (!targetTypeMembers.HasOperatorOverload(targetTypeSymbol, "op_LessThanOrEqual"))
        {
            yield return $"""
                
                public static bool operator <=({info.Target.Identifier} a, {info.Target.Identifier} b) => a.CompareTo(b) <= 0;
            """;
        }
    }

    private static IEnumerable<string> GetInterfaceSymbols(StronglyTypedTypeInfo info, IEnumerable<ISymbol> symbols, ITypeSymbol underlyingTypeSymbol)
    {
        foreach (var symbol in symbols)
        {
            if (symbol is not IMethodSymbol method)
            {
                yield return $"\n\t// Missing implementation for {symbol.OriginalDefinition.ToString()}";
                continue;
            }

            yield return method switch
            {

                { Name: "Parse", Parameters: { Length: 2 } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringParse(info, method, underlyingTypeSymbol),
                { Name: "TryParse", Parameters: { Length: 3 } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringTryParse(info, method, underlyingTypeSymbol),

                { Name: "Parse", Parameters: { Length: 2 } } => GetParse(info, method, underlyingTypeSymbol),
                { Name: "TryParse", Parameters: { Length: 3 } } => GetTryParse(info, method, underlyingTypeSymbol),

                { Name: "CompareTo", ContainingType: { IsGenericType: true } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringCompareToOfT(info, method, underlyingTypeSymbol),
                { Name: "CompareTo", ContainingType: { IsGenericType: false } } when underlyingTypeSymbol.SpecialType is SpecialType.System_String => GetStringCompareTo(info, method, underlyingTypeSymbol),

                { Name: "CompareTo", ContainingType: { IsGenericType: true } } => GetCompareToOfT(info, method, underlyingTypeSymbol),
                { Name: "CompareTo", ContainingType: { IsGenericType: false } } => GetCompareTo(info, method, underlyingTypeSymbol),
                { Name: "ToString", Parameters: { Length: 2 } } => GetToString(info, method, underlyingTypeSymbol),
                { Name: "TryFormat", Parameters: { Length: 4 } } => GetTryFormat(info, method, underlyingTypeSymbol),

                _ => $"\n\t// Missing implementation for {symbol.OriginalDefinition.ToString()}",
            };
        }
    }


    private const string ValidationResultTypeName = "System.ComponentModel.DataAnnotations.ValidationResult";

    // Validate reports the failures IsValueValid throws for as ValidationResults, so ASP.NET Core
    // validation can answer with a 400 instead of an exception, and evaluates the attributes that
    // IsValueValid cannot: those needing a ValidationContext (STP005) get the one the caller
    // passes in. It is only emitted when the user declared IValidatableObject themselves (see
    // Parser.ShouldGenerateValidate). By the time it runs, the JSON converter or TryParse has
    // already replaced an invalid payload with Empty, so the value being validated is usually the
    // default value, and it is reported like any other.
    //
    // The wrapped value is always read as this.<parameter> and every name the method introduces
    // is kept clear of the positional parameter and the user's members, so a parameter called
    // validationContext or result0 neither shadows nor is shadowed by them.
    private static IEnumerable<string> GetValidateMethod(StronglyTypedTypeInfo info, IEnumerable<ISymbol> targetTypeMembers, bool generatesValidate, bool hasUserDeclaredIsValueValid, ValidationAttributeModel validationAttributes)
    {
        if (!generatesValidate)
        {
            yield break;
        }

        var parameterName = info.Parameter.Identifier.Text;
        var value = $"this.{parameterName}";
        var reservedNames = new HashSet<string>(targetTypeMembers.Select(member => member.Name), StringComparer.Ordinal) { parameterName };
        var contextName = Parser.GetUnusedName("validationContext", reservedNames);
        var signature = $"public System.Collections.Generic.IEnumerable<{ValidationResultTypeName}> Validate(System.ComponentModel.DataAnnotations.ValidationContext {contextName})";
        var emptyResults = $"System.Array.Empty<{ValidationResultTypeName}>()";
        var attributes = GetInvariantAttributes(validationAttributes, hasUserDeclaredIsValueValid);
        var contextAttributes = GetContextAttributes(validationAttributes, generatesValidate);

        if (!hasUserDeclaredIsValueValid && attributes.IsEmpty && contextAttributes.IsEmpty)
        {
            yield return $"""

                    {signature}
                        => {emptyResults};
                """;
            yield break;
        }

        // A hand-written IsValueValid only explains a failure through its exception, so the
        // throwing overload is the one whose message is reported. ArgumentException is what the
        // README shows users throwing; ValidationException is what the attribute-generated method
        // throws and what a user copying it would use. Anything else is a bug in the user's method
        // and is left to propagate. The fallback message is the documented literal, whatever the
        // positional parameter is called.
        var invalidValueMessage = "\"Value is not valid.\"";
        var reportedExceptions = "System.ArgumentException or System.ComponentModel.DataAnnotations.ValidationException";

        if (hasUserDeclaredIsValueValid && contextAttributes.IsEmpty)
        {
            var exceptionName = Parser.GetUnusedName("ex", reservedNames);
            yield return $$"""

                    {{signature}}
                    {
                        try
                        {
                            if (IsValueValid({{value}}, throwIfInvalid: true)) return {{emptyResults}};
                        }
                        catch (System.Exception {{exceptionName}}) when ({{exceptionName}} is {{reportedExceptions}})
                        {
                            return new[] { new {{ValidationResultTypeName}}({{exceptionName}}.Message) };
                        }
                        return new[] { new {{ValidationResultTypeName}}({{invalidValueMessage}}) };
                    }
                """;
            yield break;
        }

        // Same flat layout as the attribute-generated IsValueValid: one local per check and every
        // check evaluated so a single round trip reports all failures. The checks are the
        // hand-written IsValueValid or the attributes it replaces, then the context attributes.
        // The result array is sized exactly and only created on failure, so a valid value
        // allocates nothing.
        var validators = validationAttributes.ValidatorsTypeName;
        var resultNames = new List<string>();
        var source = new StringBuilder();
        source.Append($"\n    {signature}\n    {{");

        if (hasUserDeclaredIsValueValid)
        {
            var resultName = Parser.GetUnusedName("result", reservedNames);
            var exceptionName = Parser.GetUnusedName("ex", reservedNames);
            resultNames.Add(resultName);
            source.Append($$"""

                        {{ValidationResultTypeName}}? {{resultName}} = null;
                        try
                        {
                            if (!IsValueValid({{value}}, throwIfInvalid: true)) {{resultName}} = new {{ValidationResultTypeName}}({{invalidValueMessage}});
                        }
                        catch (System.Exception {{exceptionName}}) when ({{exceptionName}} is {{reportedExceptions}})
                        {
                            {{resultName}} = new {{ValidationResultTypeName}}({{exceptionName}}.Message);
                        }

                """);
        }

        foreach (var attribute in attributes)
        {
            var resultName = Parser.GetUnusedName($"result{attribute.Index}", reservedNames);
            resultNames.Add(resultName);
            source.Append($"\n        var {resultName} = {validators}.{attribute.FieldName}.GetValidationResult({value}, {contextName});");
            source.Append($"\n        if ({resultName} == {ValidationResultTypeName}.Success) {resultName} = null;");
        }

        foreach (var attribute in contextAttributes)
        {
            var resultName = Parser.GetUnusedName($"contextResult{attribute.Index}", reservedNames);
            resultNames.Add(resultName);
            source.Append($"\n        var {resultName} = {validators}.{attribute.FieldName}.GetValidationResult({value}, {contextName});");
            source.Append($"\n        if ({resultName} == {ValidationResultTypeName}.Success) {resultName} = null;");
        }

        var resultsName = Parser.GetUnusedName("results", reservedNames);
        var indexName = Parser.GetUnusedName("index", reservedNames);
        source.Append($"\n\n        if ({string.Join(" && ", resultNames.Select(name => $"{name} is null"))}) return {emptyResults};");
        source.Append($"\n\n        var {resultsName} = new {ValidationResultTypeName}[{string.Join(" + ", resultNames.Select(name => $"({name} is null ? 0 : 1)"))}];");
        source.Append($"\n        var {indexName} = 0;");

        foreach (var name in resultNames)
        {
            source.Append($"\n        if ({name} is not null) {resultsName}[{indexName}++] = {name};");
        }

        source.Append($"\n        return {resultsName};\n    }}");

        yield return source.ToString();
    }

    private static string GetParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""

            public static {{info.Target.Identifier}} Parse({{method.Parameters[0]}}, {{method.Parameters[1]}})
            {
                var rawValue = {{underlyingTypeSymbol.ToDisplayString()}}.Parse({{method.Parameters[0].Name}}, {{method.Parameters[1].Name}});
                IsValueValid(rawValue, throwIfInvalid: true);
                return new {{info.Target.Identifier}}(rawValue);
            }
        """;

    private static string GetTryParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""

            public static bool TryParse({{method.Parameters[0]}}, {{method.Parameters[1]}}, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] {{method.Parameters[2]}})
            {
                if ({{underlyingTypeSymbol.ToDisplayString()}}.TryParse({{method.Parameters[0].Name}}, {{method.Parameters[1].Name}}, out var rawValue) && IsValueValid(rawValue, throwIfInvalid: false))
                {
                    {{method.Parameters[2].Name}} = new {{info.Target.Identifier}}(rawValue);
                    return true;
                }

                {{method.Parameters[2].Name}} = {{info.Target.Identifier}}.Empty;
                return false;
            }
        """;

    private static string GetStringParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
    {
        var rawValueString = method.Parameters[0].Type switch
        {
            { SpecialType: SpecialType.System_String } => $"{method.Parameters[0].Name}",
            _ => $"{method.Parameters[0].Name}.ToString()",
        };

        return $$"""

            public static {{info.Target.Identifier}} Parse({{method.Parameters[0]}}, {{method.Parameters[1]}})
            {
                var rawValue = {{rawValueString}};
                IsValueValid(rawValue, throwIfInvalid: true);
                return new {{info.Target.Identifier}}(rawValue);
            }
        """;
    }

    private static string GetStringTryParse(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
    {
        var rawValueString = method.Parameters[0].Type switch
        {
            { SpecialType: SpecialType.System_String } => $"{method.Parameters[0].Name}",
            _ => $"{method.Parameters[0].Name}.ToString()",
        };
        return $$"""

            public static bool TryParse({{method.Parameters[0]}}, {{method.Parameters[1]}}, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] {{method.Parameters[2]}})
            {
                if ({{rawValueString}} is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
                {
                    {{method.Parameters[2].Name}} = new {{info.Target.Identifier}}(rawValue);
                    return true;
                }

                {{method.Parameters[2].Name}} = {{info.Target.Identifier}}.Empty;
                return false;
            }
        """;
    }

    private static string GetStringCompareToOfT(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
    => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
            => ({{info.Parameter.Identifier}} ?? string.Empty).CompareTo({{method.Parameters[0].Name}}.{{info.Parameter.Identifier}});
    """;

    private static string GetStringCompareTo(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
        {
            if ({{method.Parameters[0].Name}} is null)
            {
                return 1;
            }

            if ({{method.Parameters[0].Name}} is {{info.Target.Identifier}} other)
            {
                return ({{info.Parameter.Identifier}} ?? string.Empty).CompareTo(other.{{info.Parameter.Identifier}});
            }

            return (({{method.ContainingType.ToDisplayString()}})({{info.Parameter.Identifier}} ?? string.Empty)).CompareTo({{method.Parameters[0].Name}});
        }
    """;

    private static string GetCompareToOfT(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
            => {{info.Parameter.Identifier}}.CompareTo({{method.Parameters[0].Name}}.{{info.Parameter.Identifier}});
    """;

    private static string GetCompareTo(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public int CompareTo({{method.Parameters[0]}})
        {
            if ({{method.Parameters[0].Name}} is null)
            {
                return 1;
            }

            if ({{method.Parameters[0].Name}} is {{info.Target.Identifier}} other)
            {
                return {{info.Parameter.Identifier}}.CompareTo(other.{{info.Parameter.Identifier}});
            }

            return (({{method.ContainingType.ToDisplayString()}}){{info.Parameter.Identifier}}).CompareTo({{method.Parameters[0].Name}});
        }
    """;

    private static string GetToString(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public string ToString({{method.Parameters[0]}}, {{method.Parameters[1]}})
            => {{info.Parameter.Identifier}}.ToString({{method.Parameters[0].Name}}, {{method.Parameters[1].Name}});
    """;

    private static string GetTryFormat(StronglyTypedTypeInfo info, IMethodSymbol method, ITypeSymbol underlyingTypeSymbol)
        => $$"""
        
        public bool TryFormat({{method.Parameters[0]}}, {{method.Parameters[1]}}, {{method.Parameters[2]}}, {{method.Parameters[3]}})
            => (({{method.ContainingType.ToDisplayString()}}){{info.Parameter.Identifier}}).TryFormat({{method.Parameters[0].Name}}, out {{method.Parameters[1].Name}}, {{method.Parameters[2].Name}}, {{method.Parameters[3].Name}});
    """;

    // The converter is declared by attribute instead of being emitted per type so the generated
    // code stays trim/AOT clean, and so the same converter can be declared by hand for types that
    // are serialized through a JsonSerializerContext.
    private static IEnumerable<string> GetJsonConverterAttribute(JsonConverterSupport jsonConverterSupport, string targetTypeName, string underlyingTypeName)
    {
        if (jsonConverterSupport is not JsonConverterSupport.GenerateAttribute)
        {
            yield break;
        }

        yield return $$"""
            [System.Text.Json.Serialization.JsonConverterAttribute(typeof({{StronglyTypedJsonConverter}}<{{targetTypeName}}, {{underlyingTypeName}}>))]
            """;
    }
}