name: "Prepare Release Action"
description: "Composite action to prepare a release"

inputs:
  releaseType:
    description: "Type of release"
    required: true
    default: "minor"
  projectName:
    description: "Name of the project to prepare release for"
    required: true

secrets:
  PAT_FOR_GIT_CONTENT_OPS:
    description: "Personal Access Token for git operations"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Configure GIT
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Prepare release
      id: prepare-release
      run: |
        cd ${{ inputs.projectName }}
        dotnet tool restore
        RELEASE_INFO=$(dotnet nbgv prepare-release --versionIncrement ${{ inputs.releaseType }} --commit-message-pattern "${{ inputs.projectName }} - {0} release" --format json)
        echo "RELEASE_INFO<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_INFO" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_INFO" | jq .

    - name: Extract branch info
      id: extract-branch
      shell: bash
      run: |
        RELEASE_INFO='${{ steps.prepare-release.outputs.RELEASE_INFO }}'
        NEW_BRANCH=$(echo "$RELEASE_INFO" | jq -r '.NewBranch.Name')
        echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_OUTPUT
        echo "New branch created: $NEW_BRANCH"

    - name: Push release branch
      env:
        PAT_TOKEN: ${{ secrets.PAT_FOR_GIT_CONTENT_OPS }}
      run: |
        if [[ "${{ steps.extract-branch.outputs.NEW_BRANCH }}" != "null" ]]; then
          git push https://${PAT_TOKEN}@github.com/${{ github.repository }}.git ${{ steps.extract-branch.outputs.NEW_BRANCH }}
          echo "Pushed new branch: ${{ steps.extract-branch.outputs.NEW_BRANCH }}"
        else
          echo "No new branch was created"
        fi

    - name: Checkout repository again
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push changes to main
      run: git push origin main
