//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace StronglyTypedPrimitives;

public interface IStronglyTypedPrimitive
{
}

public interface IStronglyTypedPrimitive<TPrimitiveType> : IStronglyTypedPrimitive
{
    static abstract bool IsValueValid(TPrimitiveType value, bool throwIfInvalid);
}