# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: egil-strongly-typed-primitives
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/egil-strongly-typed-primitives/v*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
  TestResultsDirectory: ${{ github.workspace}}/TestResults
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  create-nuget:
    runs-on: ubuntu-latest
    if: github.event.inputs.prepare-release != 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            10.x

      - run: |
          dotnet build ./Egil.StronglyTypedPrimitives/src/Egil.StronglyTypedPrimitives.Abstractions/Egil.StronglyTypedPrimitives.Abstractions.csproj -c Release -f net9.0
          dotnet build ./Egil.StronglyTypedPrimitives/src/Egil.StronglyTypedPrimitives.Abstractions/Egil.StronglyTypedPrimitives.Abstractions.csproj -c Release -f net8.0
          dotnet build ./Egil.StronglyTypedPrimitives/src/Egil.StronglyTypedPrimitives.Abstractions/Egil.StronglyTypedPrimitives.Abstractions.csproj -c Release -f netstandard2.0
          dotnet pack ./Egil.StronglyTypedPrimitives/src/Egil.StronglyTypedPrimitives -c Release --output ${{ env.NuGetDirectory }}

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg

  validate-nuget:
    runs-on: ubuntu-latest
    if: github.event.inputs.prepare-release != 'true'
    needs: [ create-nuget ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Install nuget validator
        run: dotnet tool restore

      - name: Validate package
        shell: pwsh
        run: dotnet meziantou.validate-nuget-package (Get-ChildItem "${{ env.NuGetDirectory }}/*.nupkg") --excluded-rules IconMustBeSet

  run-test:
    runs-on: ubuntu-latest
    if: github.event.inputs.prepare-release != 'true'
    timeout-minutes: 30
    env:
      TestResultsDirectory: ${{ github.workspace }}/TestResults
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            10.x

      - name: Run tests
        run: dotnet test ./Egil.StronglyTypedPrimitives/Egil.StronglyTypedPrimitives.sln --configuration Release --logger trx --results-directory "${{ env.TestResultsDirectory }}" --collect:"XPlat Code Coverage"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          if-no-files-found: error
          retention-days: 3
          path: ${{ env.TestResultsDirectory }}/**

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: github.actor != 'dependabot[bot]' && (success() || failure()) && github.repository_owner == 'egil'
        with:
          name: test-results
          path: ${{ env.TestResultsDirectory }}/**/*.trx
          path-replace-backslashes: 'true'
          reporter: dotnet-trx

  release:
    needs: [validate-nuget, run-test]
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/heads/release/egil-strongly-typed-primitives/v')
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      - uses: ./.github/actions/release-action
        with:
          nuget_directory: ${{ env.NuGetDirectory }}
          branch_name: ${{ env.BRANCH_NAME }}