# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: egil-orleans-storage
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/egil-orleans-storage/v*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
  TestResultsDirectory: ${{ github.workspace}}/TestResults
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  create-nuget:
    runs-on: ubuntu-latest
    if: github.event.inputs.prepare-release != 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - run: |
          dotnet build ./Egil.Orleans.Storage/src/Egil.Orleans.Storage/Egil.Orleans.Storage.csproj -c Release -f net9.0
          dotnet pack ./Egil.Orleans.Storage/src/Egil.Orleans.Storage/Egil.Orleans.Storage.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg

  validate-nuget:
    runs-on: ubuntu-latest
    if: github.event.inputs.prepare-release != 'true'
    needs: [ create-nuget ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Install nuget validator
        run: dotnet tool restore

      - name: Validate package
        shell: pwsh
        run: dotnet meziantou.validate-nuget-package (Get-ChildItem "${{ env.NuGetDirectory }}/*.nupkg") --excluded-rules IconMustBeSet

  release:
    runs-on: ubuntu-latest
    needs: [validate-nuget]
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/heads/release/egil-orleans-storage/v')
    permissions:
      checks: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      - uses: ./.github/actions/release-action
        with:
          nuget_directory: ${{ env.NuGetDirectory }}
          branch_name: ${{ env.BRANCH_NAME }}