//HintName: Foo.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace SomeNamespace;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Egil.StronglyTypedPrimitives, Version=x.x.x.x, Culture=neutral, PublicKeyToken=null", "x.x.x.x")]
[global::System.Text.Json.Serialization.JsonConverterAttribute(typeof(global::Egil.StronglyTypedPrimitives.StronglyTypedJsonConverter<global::SomeNamespace.Foo, string>))]
public readonly partial record struct Foo : global::Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<string>, global::Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<global::SomeNamespace.Foo, string>, global::System.IParsable<global::SomeNamespace.Foo>, global::System.ISpanParsable<global::SomeNamespace.Foo>, global::System.IComparable<global::SomeNamespace.Foo>, global::System.IComparable
{
    public static readonly Foo Empty = default;

    public static Foo Create(string value) => new Foo(value);

    private static string ThrowIfValueIsInvalid(string value)
    {
        IsValueValid(value, throwIfInvalid: true);
        return value;
    }

    private readonly string @data = ThrowIfValueIsInvalid(Data);

    public string Data
    {
        get => @data ?? string.Empty;
        init
        {
            @data = ThrowIfValueIsInvalid(value);
        }
    }

    string global::Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<global::SomeNamespace.Foo, string>.Value => Data;

    public override string ToString() => Data ?? string.Empty;

    private static class ValueValidators
    {
        public static readonly global::System.ComponentModel.DataAnnotations.StringLengthAttribute valueValidator0 = new global::System.ComponentModel.DataAnnotations.StringLengthAttribute(10) { MinimumLength = 2 };
        public static readonly global::SomeNamespace.TenantScopedAttribute contextValueValidator0 = new global::SomeNamespace.TenantScopedAttribute();
        public static readonly global::SomeNamespace.RemoteCheckAttribute asyncValueValidator0 = new global::SomeNamespace.RemoteCheckAttribute();

        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "DisplayName is set, so the constructor's reflection fallback for it never runs.")]
        public static global::System.ComponentModel.DataAnnotations.ValidationContext CreateInvariantContext()
            => new global::System.ComponentModel.DataAnnotations.ValidationContext(new object()) { MemberName = "Data", DisplayName = "Data" };
    }

    public static bool IsValueValid(string value, bool throwIfInvalid)
    {
        var context = ValueValidators.CreateInvariantContext();
        string? error0 = null;

        if (ValueValidators.valueValidator0.GetValidationResult(value, context) is { } result0)
        {
            if (!throwIfInvalid) return false;
            error0 = result0.ErrorMessage ?? "The field Data is invalid.";
        }

        if (error0 is null) return true;

        var message = string.Empty;
        if (error0 is not null) message = error0;
        throw new global::System.ComponentModel.DataAnnotations.ValidationException(message, null, value);
    }

    public static Foo Parse(string s, global::System.IFormatProvider? provider)
    {
        var rawValue = s;
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out global::SomeNamespace.Foo result)
    {
        if (s is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }

    public static Foo Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)
    {
        var rawValue = s.ToString();
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out global::SomeNamespace.Foo result)
    {
        if (s.ToString() is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }
    
    public int CompareTo(global::SomeNamespace.Foo other)
        => (Data ?? string.Empty).CompareTo(other.Data);
    
    public int CompareTo(object? obj)
    {
        if (obj is null)
        {
            return 1;
        }

        if (obj is Foo other)
        {
            return (Data ?? string.Empty).CompareTo(other.Data);
        }

        return ((global::System.IComparable)(Data ?? string.Empty)).CompareTo(obj);
    }

    global::System.Collections.Generic.IEnumerable<global::System.ComponentModel.DataAnnotations.ValidationResult> global::System.ComponentModel.DataAnnotations.IValidatableObject.Validate(global::System.ComponentModel.DataAnnotations.ValidationContext validationContext)
    {
        var result0 = ValueValidators.valueValidator0.GetValidationResult(this.Data, validationContext);
        if (result0 == global::System.ComponentModel.DataAnnotations.ValidationResult.Success) result0 = null;
        var contextResult0 = ValueValidators.contextValueValidator0.GetValidationResult(this.Data, validationContext);
        if (contextResult0 == global::System.ComponentModel.DataAnnotations.ValidationResult.Success) contextResult0 = null;

        if (result0 is null && contextResult0 is null) return global::System.Array.Empty<global::System.ComponentModel.DataAnnotations.ValidationResult>();

        var results = new global::System.ComponentModel.DataAnnotations.ValidationResult[(result0 is null ? 0 : 1) + (contextResult0 is null ? 0 : 1)];
        var index = 0;
        if (result0 is not null) results[index++] = result0;
        if (contextResult0 is not null) results[index++] = contextResult0;
        return results;
    }

    async global::System.Collections.Generic.IAsyncEnumerable<global::System.ComponentModel.DataAnnotations.ValidationResult> global::System.ComponentModel.DataAnnotations.IAsyncValidatableObject.ValidateAsync(global::System.ComponentModel.DataAnnotations.ValidationContext validationContext, [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken)
    {
        foreach (var result in ((global::System.ComponentModel.DataAnnotations.IValidatableObject)this).Validate(validationContext))
        {
            yield return result;
        }

        var asyncResult0 = await ValueValidators.asyncValueValidator0.GetValidationResultAsync(this.Data, validationContext, cancellationToken).ConfigureAwait(false);
        if (asyncResult0 is not null && asyncResult0 != global::System.ComponentModel.DataAnnotations.ValidationResult.Success) yield return asyncResult0;
    }
    
    public static bool operator > (Foo a, Foo b) => a.CompareTo(b) > 0;                

    public static bool operator < (Foo a, Foo b) => a.CompareTo(b) < 0;                

    public static bool operator >=(Foo a, Foo b) => a.CompareTo(b) >= 0;
    
    public static bool operator <=(Foo a, Foo b) => a.CompareTo(b) <= 0;
}