//HintName: Foo.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace SomeNamespace;

[System.CodeDom.Compiler.GeneratedCodeAttribute("Egil.StronglyTypedPrimitives, Version=x.x.x.x, Culture=neutral, PublicKeyToken=null", "x.x.x.x")]
[System.Text.Json.Serialization.JsonConverterAttribute(typeof(Egil.StronglyTypedPrimitives.StronglyTypedJsonConverter<SomeNamespace.Foo, string>))]
public readonly partial record struct Foo : Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<string>, Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<SomeNamespace.Foo, string>, System.IParsable<SomeNamespace.Foo>, System.ISpanParsable<SomeNamespace.Foo>, System.IComparable<SomeNamespace.Foo>, System.IComparable
{
    public static readonly Foo Empty = default;

    public static Foo Create(string value) => new Foo(value);

    private static string ThrowIfValueIsInvalid(string value)
    {
        IsValueValid(value, throwIfInvalid: true);
        return value;
    }

    private readonly string @value = ThrowIfValueIsInvalid(Value);

    public string Value
    {
        get => @value ?? string.Empty;
        init
        {
            @value = ThrowIfValueIsInvalid(value);
        }
    }

    public override string ToString() => Value ?? string.Empty;

    private static readonly System.ComponentModel.DataAnnotations.RequiredAttribute valueValidator0 = new System.ComponentModel.DataAnnotations.RequiredAttribute();

    public static bool IsValueValid(string value, bool throwIfInvalid)
    {
        string? error0 = null;

        if (!valueValidator0.IsValid(value))
        {
            if (!throwIfInvalid) return false;
            error0 = valueValidator0.FormatErrorMessage("Value");
        }

        if (error0 is null) return true;

        var message = string.Empty;
        if (error0 is not null) message = error0;
        throw new System.ComponentModel.DataAnnotations.ValidationException(message, null, value);
    }

    public static Foo Parse(string s, System.IFormatProvider? provider)
    {
        var rawValue = s;
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(string? s, System.IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out SomeNamespace.Foo result)
    {
        if (s is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }

    public static Foo Parse(System.ReadOnlySpan<char> s, System.IFormatProvider? provider)
    {
        var rawValue = s.ToString();
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(System.ReadOnlySpan<char> s, System.IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out SomeNamespace.Foo result)
    {
        if (s.ToString() is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }
    
    public int CompareTo(SomeNamespace.Foo other)
        => (Value ?? string.Empty).CompareTo(other.Value);
    
    public int CompareTo(object? obj)
    {
        if (obj is null)
        {
            return 1;
        }

        if (obj is Foo other)
        {
            return (Value ?? string.Empty).CompareTo(other.Value);
        }

        return ((System.IComparable)(Value ?? string.Empty)).CompareTo(obj);
    }

    public System.Collections.Generic.IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(System.ComponentModel.DataAnnotations.ValidationContext validationContext)
    {
        var result0 = valueValidator0.GetValidationResult(this.Value, validationContext);
        if (result0 == System.ComponentModel.DataAnnotations.ValidationResult.Success) result0 = null;

        if (result0 is null) return System.Array.Empty<System.ComponentModel.DataAnnotations.ValidationResult>();

        var results = new System.ComponentModel.DataAnnotations.ValidationResult[(result0 is null ? 0 : 1)];
        var index = 0;
        if (result0 is not null) results[index++] = result0;
        return results;
    }

    private static readonly SomeNamespace.RemoteCheckAttribute asyncValueValidator0 = new SomeNamespace.RemoteCheckAttribute("https://example.com");
    private static readonly SomeNamespace.NotReservedAttribute asyncValueValidator1 = new SomeNamespace.NotReservedAttribute();

    public async System.Collections.Generic.IAsyncEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> ValidateAsync(System.ComponentModel.DataAnnotations.ValidationContext validationContext, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken cancellationToken)
    {
        foreach (var result in Validate(validationContext))
        {
            yield return result;
        }

        var asyncResult0 = await asyncValueValidator0.GetValidationResultAsync(this.Value, validationContext, cancellationToken).ConfigureAwait(false);
        if (asyncResult0 is not null && asyncResult0 != System.ComponentModel.DataAnnotations.ValidationResult.Success) yield return asyncResult0;

        var asyncResult1 = await asyncValueValidator1.GetValidationResultAsync(this.Value, validationContext, cancellationToken).ConfigureAwait(false);
        if (asyncResult1 is not null && asyncResult1 != System.ComponentModel.DataAnnotations.ValidationResult.Success) yield return asyncResult1;
    }
    
    public static bool operator > (Foo a, Foo b) => a.CompareTo(b) > 0;                

    public static bool operator < (Foo a, Foo b) => a.CompareTo(b) < 0;                

    public static bool operator >=(Foo a, Foo b) => a.CompareTo(b) >= 0;
    
    public static bool operator <=(Foo a, Foo b) => a.CompareTo(b) <= 0;
}