//HintName: Foo.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace SomeNamespace;

[System.CodeDom.Compiler.GeneratedCodeAttribute("Egil.StronglyTypedPrimitives, Version=x.x.x.x, Culture=neutral, PublicKeyToken=null", "x.x.x.x")]
[System.Text.Json.Serialization.JsonConverterAttribute(typeof(Egil.StronglyTypedPrimitives.StronglyTypedJsonConverter<SomeNamespace.Foo, string>))]
public readonly partial record struct Foo : Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<string>, Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<SomeNamespace.Foo, string>, System.IParsable<SomeNamespace.Foo>, System.ISpanParsable<SomeNamespace.Foo>, System.IComparable<SomeNamespace.Foo>, System.IComparable
{
    public static readonly Foo Empty = default;

    public static Foo Create(string value) => new Foo(value);

    private static string ThrowIfValueIsInvalid(string value)
    {
        IsValueValid(value, throwIfInvalid: true);
        return value;
    }

    private readonly string @value = ThrowIfValueIsInvalid(Value);

    public string Value
    {
        get => @value ?? string.Empty;
        init
        {
            @value = ThrowIfValueIsInvalid(value);
        }
    }

    public override string ToString() => Value ?? string.Empty;

    private static class ValueValidators
    {
        public static readonly global::SomeNamespace.CheckAttribute valueValidator0 = new global::SomeNamespace.CheckAttribute((string?)null);
        public static readonly global::SomeNamespace.CheckAttribute valueValidator1 = new global::SomeNamespace.CheckAttribute((int[]?)null);
        public static readonly global::SomeNamespace.CheckAttribute valueValidator2 = new global::SomeNamespace.CheckAttribute(new string?[] { "a", null });

        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "DisplayName is set, so the constructor's reflection fallback for it never runs.")]
        public static global::System.ComponentModel.DataAnnotations.ValidationContext CreateInvariantContext()
            => new global::System.ComponentModel.DataAnnotations.ValidationContext(new object()) { MemberName = "Value", DisplayName = "Value" };
    }

    public static bool IsValueValid(string value, bool throwIfInvalid)
    {
        var context = ValueValidators.CreateInvariantContext();
        string? error0 = null;
        string? error1 = null;
        string? error2 = null;

        if (ValueValidators.valueValidator0.GetValidationResult(value, context) is { } result0)
        {
            if (!throwIfInvalid) return false;
            error0 = result0.ErrorMessage;
        }

        if (ValueValidators.valueValidator1.GetValidationResult(value, context) is { } result1)
        {
            if (!throwIfInvalid) return false;
            error1 = result1.ErrorMessage;
        }

        if (ValueValidators.valueValidator2.GetValidationResult(value, context) is { } result2)
        {
            if (!throwIfInvalid) return false;
            error2 = result2.ErrorMessage;
        }

        if (error0 is null && error1 is null && error2 is null) return true;

        var message = string.Empty;
        if (error0 is not null) message = error0;
        if (error1 is not null) message = message.Length == 0 ? error1 : message + global::System.Environment.NewLine + error1;
        if (error2 is not null) message = message.Length == 0 ? error2 : message + global::System.Environment.NewLine + error2;
        throw new global::System.ComponentModel.DataAnnotations.ValidationException(message, null, value);
    }

    public static Foo Parse(string s, System.IFormatProvider? provider)
    {
        var rawValue = s;
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(string? s, System.IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out SomeNamespace.Foo result)
    {
        if (s is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }

    public static Foo Parse(System.ReadOnlySpan<char> s, System.IFormatProvider? provider)
    {
        var rawValue = s.ToString();
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(System.ReadOnlySpan<char> s, System.IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out SomeNamespace.Foo result)
    {
        if (s.ToString() is {} rawValue && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }
    
    public int CompareTo(SomeNamespace.Foo other)
        => (Value ?? string.Empty).CompareTo(other.Value);
    
    public int CompareTo(object? obj)
    {
        if (obj is null)
        {
            return 1;
        }

        if (obj is Foo other)
        {
            return (Value ?? string.Empty).CompareTo(other.Value);
        }

        return ((System.IComparable)(Value ?? string.Empty)).CompareTo(obj);
    }
    
    public static bool operator > (Foo a, Foo b) => a.CompareTo(b) > 0;                

    public static bool operator < (Foo a, Foo b) => a.CompareTo(b) < 0;                

    public static bool operator >=(Foo a, Foo b) => a.CompareTo(b) >= 0;
    
    public static bool operator <=(Foo a, Foo b) => a.CompareTo(b) <= 0;
}