//HintName: Foo.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace SomeNamespace;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Egil.StronglyTypedPrimitives, Version=x.x.x.x, Culture=neutral, PublicKeyToken=null", "x.x.x.x")]
[global::System.Text.Json.Serialization.JsonConverterAttribute(typeof(global::Egil.StronglyTypedPrimitives.StronglyTypedJsonConverter<global::SomeNamespace.Foo, int>))]
public readonly partial record struct Foo : global::Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<int>, global::Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<global::SomeNamespace.Foo, int>, global::System.IParsable<global::SomeNamespace.Foo>, global::System.ISpanParsable<global::SomeNamespace.Foo>, global::System.IUtf8SpanParsable<global::SomeNamespace.Foo>, global::System.IComparable<global::SomeNamespace.Foo>, global::System.IComparable, global::System.IFormattable, global::System.ISpanFormattable, global::System.IUtf8SpanFormattable
{
    public static readonly Foo Empty = default;

    public static Foo Create(int value) => new Foo(value);

    private static int ThrowIfValueIsInvalid(int value)
    {
        IsValueValid(value, throwIfInvalid: true);
        return value;
    }

    private readonly int @class_ = ThrowIfValueIsInvalid(@class);

    public int @class
    {
        get => @class_;
        init
        {
            @class_ = ThrowIfValueIsInvalid(value);
        }
    }

    int global::Egil.StronglyTypedPrimitives.IStronglyTypedPrimitive<global::SomeNamespace.Foo, int>.Value => @class;

    public override string ToString() => @class.ToString();

    private static class ValueValidators
    {
        public static readonly global::System.ComponentModel.DataAnnotations.RangeAttribute valueValidator0 = new global::System.ComponentModel.DataAnnotations.RangeAttribute(1, 10);
        public static readonly global::SomeNamespace.RemoteCheckAttribute asyncValueValidator0 = new global::SomeNamespace.RemoteCheckAttribute();

        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "DisplayName is set, so the constructor's reflection fallback for it never runs.")]
        public static global::System.ComponentModel.DataAnnotations.ValidationContext CreateInvariantContext()
            => new global::System.ComponentModel.DataAnnotations.ValidationContext(new object()) { MemberName = "class", DisplayName = "class" };
    }

    public static bool IsValueValid(int value, bool throwIfInvalid)
    {
        var context = ValueValidators.CreateInvariantContext();
        string? error0 = null;

        if (ValueValidators.valueValidator0.GetValidationResult(value, context) is { } result0)
        {
            if (!throwIfInvalid) return false;
            error0 = result0.ErrorMessage ?? "The field class is invalid.";
        }

        if (error0 is null) return true;

        var message = string.Empty;
        if (error0 is not null) message = error0;
        throw new global::System.ComponentModel.DataAnnotations.ValidationException(message, null, value);
    }

    public static Foo Parse(string s, global::System.IFormatProvider? provider)
    {
        var rawValue = int.Parse(s, provider);
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out global::SomeNamespace.Foo result)
    {
        if (int.TryParse(s, provider, out var rawValue) && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }

    public static Foo Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)
    {
        var rawValue = int.Parse(s, provider);
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out global::SomeNamespace.Foo result)
    {
        if (int.TryParse(s, provider, out var rawValue) && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }

    public static Foo Parse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider)
    {
        var rawValue = int.Parse(utf8Text, provider);
        IsValueValid(rawValue, throwIfInvalid: true);
        return new Foo(rawValue);
    }

    public static bool TryParse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(returnValue: false)] out global::SomeNamespace.Foo result)
    {
        if (int.TryParse(utf8Text, provider, out var rawValue) && IsValueValid(rawValue, throwIfInvalid: false))
        {
            result = new Foo(rawValue);
            return true;
        }

        result = Foo.Empty;
        return false;
    }
    
    public int CompareTo(global::SomeNamespace.Foo other)
        => @class.CompareTo(other.@class);
    
    public int CompareTo(object? obj)
    {
        if (obj is null)
        {
            return 1;
        }

        if (obj is Foo other)
        {
            return @class.CompareTo(other.@class);
        }

        return ((global::System.IComparable)@class).CompareTo(obj);
    }
    
    public string ToString(string? format, global::System.IFormatProvider? formatProvider)
        => @class.ToString(format, formatProvider);
    
    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        => ((global::System.ISpanFormattable)@class).TryFormat(destination, out charsWritten, format, provider);
    
    public bool TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        => ((global::System.IUtf8SpanFormattable)@class).TryFormat(utf8Destination, out bytesWritten, format, provider);

    public global::System.Collections.Generic.IEnumerable<global::System.ComponentModel.DataAnnotations.ValidationResult> Validate(global::System.ComponentModel.DataAnnotations.ValidationContext validationContext)
    {
        var result0 = ValueValidators.valueValidator0.GetValidationResult(this.@class, validationContext);
        if (result0 == global::System.ComponentModel.DataAnnotations.ValidationResult.Success) result0 = null;

        if (result0 is null) return global::System.Array.Empty<global::System.ComponentModel.DataAnnotations.ValidationResult>();

        var results = new global::System.ComponentModel.DataAnnotations.ValidationResult[(result0 is null ? 0 : 1)];
        var index = 0;
        if (result0 is not null) results[index++] = result0;
        return results;
    }

    public async global::System.Collections.Generic.IAsyncEnumerable<global::System.ComponentModel.DataAnnotations.ValidationResult> ValidateAsync(global::System.ComponentModel.DataAnnotations.ValidationContext validationContext, [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)
    {
        foreach (var result in Validate(validationContext))
        {
            yield return result;
        }

        var asyncResult0 = await ValueValidators.asyncValueValidator0.GetValidationResultAsync(this.@class, validationContext, cancellationToken).ConfigureAwait(false);
        if (asyncResult0 is not null && asyncResult0 != global::System.ComponentModel.DataAnnotations.ValidationResult.Success) yield return asyncResult0;
    }
    
    public static bool operator > (Foo a, Foo b) => a.CompareTo(b) > 0;                

    public static bool operator < (Foo a, Foo b) => a.CompareTo(b) < 0;                

    public static bool operator >=(Foo a, Foo b) => a.CompareTo(b) >= 0;
    
    public static bool operator <=(Foo a, Foo b) => a.CompareTo(b) <= 0;
}